// All OLED display functions
void displayWelcomeScreen();
void displayCurrentTime();
void displayNextFeedTime();
void displayKibbleAmount();
void displayModeStatus();
void displayFeedingHistory();
void displayLowFoodAlert();
void displayHealthAlert();
void updateDisplay();
void clearDisplay();
void showScreen(int screenNumber);
void displayEmergencyMessage(String message);
void displayFeedingInProgress(int amount);
void displayFeedingSuccess(int amount);
void displayCalibrationMode();
void displayBootScreen();
void displayErrorScreen(String errorMessage);
void displayMaintenanceMode();
void displayNetworkStatus(bool connected);
void displayProgressBar(int percentage, String label);
